version: '3.8'

services:
  grafana:
    image: grafana/grafana
    user: '472'
    restart: always
    networks:
      - primary_network 
      - monitoring
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config.monitoring
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  monitoring:
    external: true
  primary_network:
    driver: bridge

volumes:
  grafana_data: {}